from selenium import webdriver
opts=webdriver.ChromeOptions()
opts.add_experimental_option("detach",True)
driver=webdriver.Chrome(options=opts)
# driver.get("https://www.google.com/")
driver.get("https://github.com/kanika881/JECRC-KANIKA_GOYAL-6206937-JECT6MAROFF0274/tree/main/day2(12.03.2026)")
driver.maximize_window()
print(f"Title:{driver.title}")
print(f"url:{driver.current_url}")
print(f"NAME:{driver.name}")